config/routes.rb
Rails.application.routes.draw do
  resources :positions
  resources :boards
  resources :memberships
  resources :organizations
  resources :users

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'

  resource :session, only: [:new, :create, :delete]

  root :to => "users#new"

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :memberships
  has_many :members, through: :memberships, source: :user
  has_one :board

  validates :name, uniqueness: true,
            length: { minimum: 3}

  def to_s
    "#{name}"
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
    @board = Board.all
    @position = Position.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @position = Position.new
    if @organization.members.include? current_user
      @membership = @organization.memberships.find_by user_id:current_user.id
    else
      @membership = Membership.new
      @membership.organization = @organization
    end
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
    @board = Board.new
    @position = Position.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    @board = Board.new
    @board.organization = @organization

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :founded, :description)
    end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :founded %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>
<% if not current_user.nil? %>
    <h1>Listing Organizations</h1>

    <table class="hoverable">
      <thead>
        <tr>
          <th>Name</th>
          <th>Founded</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @organizations.each do |organization| %>
          <tr>
            <td><%= link_to organization, organization %></td>
            <td><%= organization.founded %></td>
            <td><%= organization.description %></td>
            <% if false %>
            <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
            <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Organization', new_organization_path %>
<% end %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col s12 l6 m6">
        <h2><%= @organization.name %></h2>

        <p>
          <strong>Founded:</strong>
          <%= @organization.founded %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @organization.description %>
        </p>

        <h5>Members</h5>

        <table class="striped centered">
          <thead>
          <tr>
            <th>Name</th>
            <th>City</th>
            <th>Joined</th>
          </tr>
          </thead>
          <tbody>
          <% @organization.members.each do |member| %>
              <tr>
                <td><%= link_to member.to_s, member %></td>
                    <td><%= member.city %></td>
                    <td><%= member.created_at %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
    </div>
    <div class="col s12 l6 m6">
      <% if current_user %>
          <% if @organization.members.include?(current_user) %>
              <%= form_for(@membership, method: "delete") do |f| %>
                  <%= f.hidden_field :organization_id %>
                  <%= f.submit value: "end your membership", class:"btn"  %>
              <% end %>
          <% else %>
              <%= form_for(@membership) do |f| %>
                  <%= f.hidden_field :organization_id %>
                  <%= f.submit value: "join the organization", class:"btn" %>
              <% end %>
          <% end %>
      <% end %>
      <%= link_to 'Edit', edit_organization_path(@organization), class: "btn primary"%>
    </div>
</div>

<div class="row">
  <div class="col s12 l6 m6">
        <h5>Board Members</h5>
        <%=@organization.board %>
    <table class="striped centered">
      <thead>
      <tr>
        <th>Position</th>
        <th>Name</th>
      </tr>
      </thead>
      <tbody>
      <% @organization.board.positions.each do |position|%>
          <tr>
            <td><%= position.name %></td>
            <td><%= link_to position.user, position.user %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    </div>

    <div class="col s12 l6 m6">
    <h5>Add new position and holder</h5>
    <%= form_for(@position) do |f| %>
          <%= f.hidden_field :board_id, value: @organization.board.id %>
          <%= @organization.board  %>
          <%= f.text_field :name, placeholder: "Position name" %>
          <%= f.select :user_id, options_from_collection_for_select(@organization.members, :id, :to_s, @position.user_id) %>
          <%= f.submit value: "Add board member", class:"btn btn-primary" %>
    <% end %>
  </div>

</div>

<div class="controls">
    <%= link_to 'Back', organizations_path %>
</div>