config/routes.rb
Rails.application.routes.draw do
  resources :positions
  resources :boards
  resources :memberships
  resources :organizations
  resources :users

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'

  resource :session, only: [:new, :create, :delete]

  root :to => "users#new"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jrekisteri</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <ul id="dropdown1" class="dropdown-content">
      <li><%= current_user %></li>
      <li class="divider"></li>
      <li><%= link_to '<i class="small mdi-action-account-box"></i> Profile'.html_safe, current_user%></li>
      <li><%= link_to '<i class="small mdi-navigation-chevron-right"></i> Signout'.html_safe, signout_path%></li>
    </ul>

    <nav>
      <div class="nav-wrapper">
        <div class="container">
          <a href="#" data-activates="mobile-demo" class="button-collapse right"><i class="mdi-navigation-menu"></i></a>
          <ul class="right hide-on-med-and-down">
            <li><%= link_to 'Käyttäjät', users_path %></li>
            <li><%= link_to 'Järjestöt', organizations_path %></li>
            <% if not current_user.nil? %>
                <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user %><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
            <% else %>
                <li><%= link_to 'Signin', signin_path %></li>
                <li><%= link_to 'Signup', signup_path %></li>
            <% end %>
          </ul>
          <%= link_to 'Jäsenrekisteri', root_path ,class:'brand-logo' %>
              <ul class="side-nav" id="mobile-demo">
                <li><%= link_to 'Käyttäjät', users_path %></li>
                <li><%= link_to 'Järjestöt', organizations_path %></li>
                <% if not current_user.nil? %>
                    <li><%= link_to current_user, current_user%></li>
                    <li><%= link_to 'Signout', signout_path%></li>
                <% else %>
                    <li><%= link_to 'Signin', signin_path %></li>
                    <li><%= link_to 'Signup', signup_path %></li>
                <% end %>
              </ul>
          </ul>
        </div>
      </div>
    </nav>
    <main>
        <div class="container">
            <%= yield %>
        </div>
    </main>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>